### ISSUE TITLE
Handle not well formatted dates in RSS feeds

### ISSUE THREAD

**Issue by macbre** [macbre/pelican-planet#15]
```
-> Parsing "Kringvarp Føroya" feed from <https://kvf.fo/rss/news-english> ...
CRITICAL: Unknown string format: <span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2021-05-24T11:08:00+01:00">Mán, 24 Mai 2021 11:08 GMT</span>
```

**Comment by macbre** [comment]
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.10/x64/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican/__init__.py", line 512, in main
    pelican.run()
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican/__init__.py", line 89, in run
    generators = [
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican/__init__.py", line 90, in <listcomp>
    cls(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican/generators.py", line 708, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican/generators.py", line 235, in __init__
    Generator.__init__(self, *args,
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican/generators.py", line 87, in __init__
    signals.generator_init.send(self)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican_planet/__init__.py", line 43, in generate
    planet.get_feeds()
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican_planet/planet.py", line 91, in get_feeds
    articles = self._get_articles(feed, name)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican_planet/planet.py", line 76, in _get_articles
    articles = sorted(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican_planet/planet.py", line 66, in _get_articles
    article['updated'] = make_date(article['updated'])
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pelican_planet/utils.py", line 25, in make_date
    return dtparser.parse(date_string)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ParserError("Unknown string format: %s", timestr)
```
